[build]
  functions = "lambda"
  build = "npm run prod"

# Using following lines to let clientside redirects take over.
[[redirects]]
  from = "/*"
  to = "/404"
  status = 200

# Redirect .com to .org
[[redirects]]
  from = "http://artfortibet.com/*"
  to = "https://artfortibet.org/:splat"
  status = 301
  force = true

# Redirect .com to .org
[[redirects]]
  from = "https://artfortibet.com/*"
  to = "https://artfortibet.org/:splat"
  status = 301
  force = true

# Redirect .com to .org
[[redirects]]
  from = "http://www.artfortibet.com/*"
  to = "https://artfortibet.org/:splat"
  status = 301
  force = true

# Redirect .com to .org
[[redirects]]
  from = "https://www.artfortibet.com/*"
  to = "https://artfortibet.org/:splat"
  status = 301
  force = true